### ISSUE TITLE
Support AWS SSO

### ISSUE THREAD

**Issue by iainelder** [goldfiglabs/introspector#10]
Using AWS IAM credentials, all is well:

```text
$ AWS_PROFILE=saa-gen-iam ./introspector account aws import --help
Usage: introspector.py account aws import [OPTIONS]
[...]
```

Using AWS SSO I expect to get the same result.

Instead Introspector panics with a cryptic error because the AWS Go SDK can't get credentials.

```text
$ AWS_PROFILE=saa-gen ./introspector account aws import --help
panic: EC2RoleRequestError: no EC2 instance role found
caused by: request canceled, context deadline exceeded

goroutine 1 [running]:
main.main()
	/Users/greg/workspace/introspector/launcher/main.go:208 +0x3d9
```

I believe the minimum version of the Go SDK with good support for AWS SSO is v1.2.0.

https://github.com/aws/aws-sdk-go-v2/releases/tag/v1.2.0

Can you upgrade Inspector to use at least that version?

**Comment by gsoltis** [comment]
Good suggestion, I will include that in the next release.

**Comment by gsoltis** [comment]
Can you try again with the latest release? I've updated the AWS SDK in the launcher.

**Comment by iainelder** [comment]
It works! My SSO-based profile now behaves the same way.

Thanks for dealing with this so quickly.

**Comment by iainelder** [comment]
I'm linking to the commit and the release that solve the problem:

https://github.com/goldfiglabs/introspector/commit/dc768d72709eedeffa269b37de09fa87a4e04e66

https://github.com/goldfiglabs/introspector/releases/tag/v0.1.2
