### ISSUE TITLE
introspector is not authorized to perform: acm-pca:ListCertificateAuthorities

### ISSUE THREAD

**Issue by iainelder** [goldfiglabs/introspector#11]
It looks like the recommended permissions are lacking acm-pca:ListCertificateAuthorities.

I don't see it listed in SecurityAudit, ViewOnlyAccess or Introspector-Ro-Additions.

Introspector is failing for me because of that.

```
$ AWS_PROFILE=introspector ./introspector account aws import
Add AWS account 01234567890 using identity arn:aws:iam::01234567890:user/introspector? [Y/n] Y
[2021-03-19 19:09:19,636] {__init__.py:88} ERROR - exception caught in import
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/app/introspector/aws/svc.py", line 215, in _async_proxy
    for resource_name, raw_resources in import_fn(service_proxy, region,
  File "/app/introspector/aws/acm_pca.py", line 34, in _import_acm_pca_region
    yield from _import_certificate_authorities(proxy)
  File "/app/introspector/aws/acm_pca.py", line 23, in _import_certificate_authorities
    certificate_authorities_resp = proxy.list('list_certificate_authorities')
  File "/app/introspector/aws/fetch.py", line 396, in list
    return self._impl.list(resource, kwargs)
  File "/app/introspector/aws/fetch.py", line 100, in list
    raise e
  File "/app/introspector/aws/fetch.py", line 58, in list
    result = iterator.build_full_result()
  File "/usr/local/lib/python3.9/site-packages/botocore/paginate.py", line 449, in build_full_result
    for response in self:
  File "/usr/local/lib/python3.9/site-packages/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/paginate.py", line 332, in _make_request
    return self._method(**current_kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the ListCertificateAuthorities operation: User: arn:aws:iam::01234567890:user/introspector is not authorized to perform: acm-pca:ListCertificateAuthorities
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/introspector/__init__.py", line 85, in collect_exceptions
    _ = result.result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 440, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the ListCertificateAuthorities operation: User: arn:aws:iam::01234567890:user/introspector is not authorized to perform: acm-pca:ListCertificateAuthorities
```

The above errors repeat several times and finally it prints results.

```text
Results - Import #1
  Start:  2021-03-19 19:09:07
  End:  2021-03-19 19:09:51
  Errors:  16
  Resources added:  0
  Resources removed:  0
  Resources updated:  0
    Attributes added:  0
    Attributes removed:  0
    Attributes updated:  0
```

**Comment by gsoltis** [comment]
Ah, this is actually handled in the latest code, but not in the latest build / docker image. It looks like it is time for me to make a build, as well as update the documentation.

**Comment by gsoltis** [comment]
The latest release both documents the additional permissions required, and *should* fail more gracefully on missing permissions (this part still needs work to be comprehensive). You may need to do `docker pull goldfig/introspector:latest` to get the latest image. Version numbers in the compose file coming soon :) (#12)

**Comment by iainelder** [comment]
> You may need to do docker pull goldfig/introspector:latest to get the latest image.

I updated the introspector Docker image to e934e4551c83.

It works!

```
$ AWS_PROFILE=introspector ./introspector account aws import
[2021-03-20 14:23:25,481] {resource.py:65} WARNING - Missing target for relation arn:aws:cloudwatch:us-east-1:01234567890:alarm:BillingAlert fires-on [metrics/us-east-1/None/None/] (1)
Results - Import #2
  Start:  2021-03-20 14:20:27
  End:  2021-03-20 14:23:30
  Errors:  0
  Resources added:  273
  Resources removed:  0
  Resources updated:  3
    Attributes added:  30
    Attributes removed:  0
    Attributes updated:  0
```

The warning message "Missing target for relation ... alarm ... fires-on"; is something wrong with the alarm configuration? Or is something wrong with the table in PostgreSQL that it's being written to?

> The latest release both documents the additional permissions required, and should fail more gracefully on missing permissions (this part still needs work to be comprehensive)

I didn't update the poicy Introspector-Ro-Additions in my AWS account to the latest version that includes the titular permissions.

https://github.com/goldfiglabs/introspector/blob/e41fb9aa2af2e79932adf4630279d5feee08ffc2/permission-policies/aws-introspector-ro.json

The output gives no indication that the PCA permissions are still lacking. Is it just skipping silently over anything it can't check?

It would be nice if this would generate at least a warning so that I know that something might be missing from the database.

(If you prefer that I open new issues to deal with these points just say and I'll do it :-))

**Comment by gsoltis** [comment]
Glad to hear it's working. 

The code does currently just swallow the error in the case of missing permissions, I agree that a warning would be a good idea. I think eventually we will want to record what was skipped as part of the import.

For some of the calculated relations, as you can see from the `None` token, we don't know the correct thing to relate them to (or it might not exist). These shouldn't actually be warnings at this point. If we can't construct the URI for a relation, we should not then be logging that we can't find the target...

Please do file additional issues, they're super helpful!

**Comment by iainelder** [comment]
Opened #13 and #14 to address the logging issues. I'll close this one.

Thanks!
