### ISSUE TITLE
How to find long policy documents?

### ISSUE THREAD

**Issue by iainelder** [goldfiglabs/introspector#15]
IAM limits the length of a managed policy document after removing whitespace to 6144 characters.

Uncontrolled growth in of a policy document will eventually lead to an error when the length exceeds the limit. This will impair or block anything depending on the policy to provide it permissions.

I've tried querying the instrospector database like this to find such long documents.

```sql
SELECT document::text FROM aws_iam_policyversion;
```

Unfortunately the jsonb type when cast to text puts spaces after the commas and the colons.

I don't see any other way in SQL to get the compact string representation (like `jq -c`).

I have a custom Python script for doing it which uses a function like this:

```python
def get_default_document_for_policy(policy):

    resp = boto3.client("iam").get_policy_version(
        PolicyArn=policy["Arn"], VersionId=policy["DefaultVersionId"]
    )

    return json.dumps(resp["PolicyVersion"]["Document"], separators=(",", ":"))
```

How would I adapt this to Introspector?

**Comment by gsoltis** [comment]
I'm not sure there's a native postgresql way to do that. You could try something like: 

`PGPASSWORD=introspector psql -d introspector -U introspector -h localhost --quiet -t -c "SELECT document::text FROM aws_iam_policyversion" | jq -c` to use `jq`. Would that work for you?

**Comment by gsoltis** [comment]
Actually, if you're using the postgres from the `docker-compose` file, or any postgres with `plv8` available, try this:

```
CREATE EXTENSION IF NOT EXISTS plv8;
CREATE OR REPLACE FUNCTION policy_length (policy JSONB)
RETURNS INT AS $$
return JSON.stringify(policy).length;
$$ LANGUAGE plv8 IMMUTABLE STRICT;

SELECT policy_length(document) FROM aws_iam_policyversion;
```

**Comment by iainelder** [comment]
@gsoltis Thanks! A columnar solution is exactly what I was looking for.

I was going to suggest PL/Python, but PL/v8 is preferable as it is a trusted language.

With your policy_length function in place, Introspector can report on long policy documents with a query like this:

```sql
WITH pol_len AS (
  SELECT
    policyname AS policy,
    LENGTH("document"::text) AS casted, -- naive casted length
    policy_length("document") AS metered -- length metered by AWS
  FROM       aws_iam_policyversion as v
  INNER JOIN aws_iam_policy as p on p._id = v._policy_id
  WHERE
    v.isdefaultversion = true
)
SELECT
  policy,
  casted,
  metered,
  ROUND((100.0 * (casted - metered)) / metered) AS over_pct, -- percentage overestimage of the naive length
  ROUND((100.0 * metered) / 6144) AS quota -- percentage of the metered quota used
FROM pol_len
ORDER BY
  metered DESC,
  policy;
```

I've added the casted and over_pct columns to compare it to the naive method.

|                      policy                      | casted | metered | over_pct | quota |
|--------------------------------------------------|--------|---------|----------|-------|
| AWSSupportServiceRolePolicy                      |  56075 |   54358 |        3 |   885 |
| SecurityAudit                                    |   9634 |    9291 |        4 |   151 |
| AWS_ConfigRole                                   |   5563 |    5370 |        4 |    87 |
| ViewOnlyAccess                                   |   5562 |    5348 |        4 |    87 |
| AWSTrustedAdvisorServiceRolePolicy               |   2573 |    2487 |        3 |    40 |
| AWSSSOServiceRolePolicy                          |   2142 |    2033 |        5 |    33 |
| ConfigConformsServiceRolePolicy                  |   2016 |    1933 |        4 |    31 |
| AWSConfigMultiAccountSetupPolicy                 |   1345 |    1287 |        5 |    21 |
| Introspector-Ro-Additions                        |   1055 |    1009 |        5 |    16 |
| AWSSecurityHubServiceRolePolicy                  |    899 |     866 |        4 |    14 |
| AWSOrganizationsServiceTrustPolicy               |    359 |     341 |        5 |     6 |
| CloudFormationStackSetsOrgAdminServiceRolePolicy |    324 |     305 |        6 |     5 |
| AdministratorAccess                              |     93 |      85 |        9 |     1 |

We can see that the naive method is not terrible, but will overestimate the metered length by about 3-5%.

As we can see with SecurityAudit and AWSSupportServiceRolePolicy, AWS-managed policies can grow beyond 6144 characters.

AWS_ConfigRole and ViewOnlyAccess role are occupying 87% of the quota. If they were customer-managed policies, I would need to think carefully about adding more policy elements to them, and perhaps think about splitting them into smaller policies.

**Comment by iainelder** [comment]
@gsoltis would you consider adding a relation with columns for system-wide constants such the one discussed here?

It would avoid having a magic number in my script and it would provide a single place to update the value if AWS ever increased the quota.

https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_iam-quotas.html

The quotas for IAM are not exposed, as far as I know, by the service quotas API.

**Comment by gsoltis** [comment]
Do you mean add a fixture for constants? As in,

```
CREATE TABLE aws_iam_constants (
  name TEXT,
  value INT
)
``` 
or something like that?

**Comment by iainelder** [comment]
Yes, but with one column for each constant in a single row.

Something like this:

```sql
CREATE OR REPLACE VIEW aws_iam_constants
AS
SELECT
  CAST(6144 AS INT) AS managed_policy_max_size,
  CAST(10 AS INT) AS managed_policy_max_per_entity,
  CAST(5120 AS INT) AS group_policy_max_size,
  CAST(10240 AS INT) AS role_policy_max_size,
  CAST(2048 AS INT) AS user_policy_max_size;
```

Which could be queried like this:

```sql
SELECT managed_policy_max_size FROM aws_iam_constants;
```

**Comment by iainelder** [comment]
Great, thanks for adding the table with all the constants! It will enable many other queries that check against quotas.

On a personal note, I'm excited about the potential of Introspector as a complement to AWS Config for inventory and compliance.

It's going to save me so much time that would have been spent writing variations of the same basic Python script to collect and analyze data from the AWS APIs.

Thank you @gsoltis and @vikrum .

**Comment by gsoltis** [comment]
And thank you as well, glad to hear Introspector can be helpful!
