### ISSUE TITLE
Skip AWS Organizations

### ISSUE THREAD

**Issue by nyetsche** [goldfiglabs/introspector#2]
The tool looks interesting, but assumes that there's an AWS organization in place (and that it's accessible to the user). Is there a plan to remove that requirement? https://github.com/goldfiglabs/goldfig/blob/main/goldfig/aws/__init__.py#L92

Thanks for publishing your work.

**Comment by gsoltis** [comment]
Yes! Coming in the next update. The tool will synthesize a dummy organization in that case. We've been testing that scenario for the past few days and will publish the changes soon.

**Comment by gsoltis** [comment]
This is fixed in the latest push. Accounts that are not tied to an organization now get dummy data that allows the import to proceed.
