### ISSUE TITLE
Help message shouldn't depend on valid AWS profile

### ISSUE THREAD

**Issue by iainelder** [goldfiglabs/introspector#22]
Just a small usability feature to make introspector easier to learn.

I don't have a default AWS profile in my environment.

When I set an AWS profile for the command the help message does appear.

```
$ AWS_PROFILE=introspector ./introspector account aws import --help
Usage: introspector.py account aws import [OPTIONS]

  Imports the assets from an AWS account into introspector

Options:
  -f, --force         Skip prompts for adding accounts
  -s, --service TEXT  Only import the specified service(s)
  -g, --gov-cloud     Set this flag to import a govcloud account
  --help              Show this message and exit.
```

I would expect the help message to appear without an AWS profile set, but instead it prints an error.

```text
$ ./introspector account aws import --help
panic: no EC2 IMDS role found, operation error ec2imds: GetMetadata, request canceled, context deadline exceeded

goroutine 1 [running]:
main.main()
	/Users/greg/workspace/introspector/launcher/main.go:208 +0x3d9
```

**Comment by gsoltis** [comment]
Agreed. Definitely ought to be friendlier.

**Comment by iainelder** [comment]
@gsoltis, #24 definitely looks better than the slightly cryptic error that Go generates by default, so thanks for that.

But what I was mean here is that when the `--help` flag is set the help message should be shown regardless of the state of the credentials.

Can you make it always print help message when the `--help` option is set?

The AWS CLI is a good example of the behavior I'm expecting.

No default profile set, so the actual `describe-instances` API fails.

```text
$ aws ec2 describe-instances

You must specify a region. You can also configure your region by running "aws configure".
```

But `describe-instances help` shows documentation for the describe-instances API even when it can't find credentials.

```text
$ aws ec2 describe-instances help
[paged output]
DESCRIBE-INSTANCES()                                      DESCRIBE-INSTANCES()



NAME
       describe-instances -

DESCRIPTION
       Describes the specified instances or all instances.
[...]
```

I see in the source the help is actually implemented using Python's Click package. I'm not familiar with it, so I don't know how much control you have over this behavior.

https://github.com/goldfiglabs/introspector/blob/57318e115eee2878e8a51709eded638a335b895d/introspector/cli/account/aws.py#L30-L31

**Comment by gsoltis** [comment]
Ah, got it. Currently slightly awkward due to the split between the launcher and the docker-wrapped python program. But should be doable, and makes sense.

**Comment by iainelder** [comment]
Great! The "help passthrough" was exactly the thing I was looking for (but didn't know the implementation well enough to find the right words).
