### ISSUE TITLE
ERROR: Version in "./docker-compose.yml" is unsupported

### ISSUE THREAD

**Issue by iainelder** [goldfiglabs/introspector#9]
My Docker and Docker Compose versions are the same ones given in the prerequisites.

(Incidentally, these are the versions installed by apt from the Ubuntu repository.)

```text
$ lsb_release --description --short
Ubuntu 20.04.2 LTS
$ docker --version
Docker version 19.03.8, build afacb8b7f0
$ docker-compose --version
docker-compose version 1.25.0, build unknown
```

Yet when I follow the "getting started" steps I get an error about an unsupported version.

```text
$ cd ~/tmp
$ curl -sSLO https://github.com/goldfiglabs/introspector/releases/latest/download/introspector_linux.zip
$ unzip -oq introspector_linux.zip 
$ docker-compose up -d
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

What versions do I really need to use?

**Comment by gsoltis** [comment]
Hmm, the linked [version matrix](https://docs.docker.com/compose/compose-file/) implies that `docker engine 19.03.0+` should work with compose version `3.8`, although it seems like maybe your version of `docker-compose` might be too old. The `docker-compose` [release notes](https://docs.docker.com/compose/release-notes/#features-4) indicate support for file version 3.8 was added in `docker-compose v1.25.5`. 

Can you try upgrading `docker-compose` to at least that version?

**Comment by iainelder** [comment]
The version in the current file is 3.8.

https://github.com/goldfiglabs/introspector/blob/daa824d859e42f703782ab7952b242524cbdc1b7/docker-compose.yml#L1

The Docker Compose documentation is sadly no help here.

https://docs.docker.com/compose/compose-file/compose-versioning/

All it says about version 3.8 is that it requires Docker Engine version 19.03. I have that and here we are :-)

They stopped documenting the required docker-compose version after compose file version 2.4.

---

Anyway, I worked around the problem by removing the apt-installed docker-compose and replacing it with the latest version from PyPI installed with pipx.

```text
$ sudo apt remove docker-compose
[...]
$ pipx install docker-compose
  installed package docker-compose 1.28.5, Python 3.8.5
  These apps are now globally available
    - docker-compose
done! ✨ 🌟 ✨
$ hash -r
$ docker-compose up -d
Creating network "tmp_default" with the default driver
[...]
Creating tmp_db_1 ... done
Creating tmp_introspector_1 ... done
```

**Comment by iainelder** [comment]
@gsoltis thanks for such a quick reply! You beat me to it :-)

And it turns out I hadn't checked the version number carefully enough.

1.25.0 <> 1.25.5
